services:

  ##########################################################
  # AUTHOR START
  ##########################################################
  author:
    image: ${AUTHOR_IMAGE}
    hostname: author
    restart: unless-stopped
    ports:
      - ${AUTHOR_PORT}:8080
      - ${AUTHOR_DEBUG_PORT}:58242
    environment:
      - TZ      
      - AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,dev,dynamicmedia_scene7,nosamplecontent
      - AEM_JVM_OPTS=-server -Xms248m -Xmx2048m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58242    
    volumes:
      - author-data:/aem/crx-quickstart/repository
    networks:
      - author-network
      - publish-network
      - internal
      - default
  ##########################################################
  # AUTHOR END
  ##########################################################

  ##########################################################
  # PUBLISH START
  ##########################################################
  publish:
    image: ${PUBLISH_IMAGE}
    hostname: publish
    restart: unless-stopped
    ports:
      - ${PUBLISH_PORT}:8080
      - ${PUBLISH_DEBUG_PORT}:58242
    environment:
      - TZ
      - AEM_RUNMODE=-Dsling.run.modes=publish,crx3,crx3tar,dev,dynamicmedia_scene7,nosamplecontent
      - AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58242
    volumes:
      - publish-data:/aem/crx-quickstart/repository
    networks:
      - publish-network
      - internal
      - default
  ##########################################################
  # PUBLISH END
  ##########################################################

networks:
  default:
  internal:
  author-network:
  publish-network:

volumes:
  author-data:
  publish-data:
